---
title: "R Assignment"
author: "Group 1"
date: "2024-06-14"
output:
  pdf_document:
    latex_engine: xelatex
    includes:
      in_header: header.tex
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


``` {r Assignment Script}
#------------------------------------------------------------------------------------------#


library(tidyverse)
library(dplyr)
library(DescTools)
library(ggplot2)
library(scales)

#------------------------------------------------------------------------------------------#
players_ds <- read.csv("R Assignment/players.csv")

# Print the structure of your dataset
str(players_ds)

#------------------------------------------------------------------------------------------#

# List the variables in your dataset
players_ds_vars <- names(players_ds)
print(players_ds_vars)

#------------------------------------------------------------------------------------------#

# Print the top 15 rows of your dataset
players_ds_top15 <- head(players_ds,15)
print (players_ds_top15)

head(players_ds,15)

#------------------------------------------------------------------------------------------#

# Write a user defined function using any of the variables from the data set.

# Function to return the no of players having market value greater than 10 million
player_count <- function (market_value, threshold){
  count <- 0
  for (mv in market_value){
    if (!is.na(mv) && mv > threshold){
      count <- count +1
    }
  }
  return(count)
}
threshold <- 10000000  
players_above_threshold <- player_count(players_ds$market_value_in_eur,threshold)

print(paste("The number of players with market value above 10 million are : ", players_above_threshold))

#------------------------------------------------------------------------------------------#

#Use data manipulation techniques and filter rows based on any logical criteria that exist in your dataset.
#Players who are taller than 190 cm and have market value above 5 million euros
filtered_players <- players_ds %>% filter(height_in_cm > 190, market_value_in_eur > 5000000)
print(paste("Players taller than 190cm and market value above 5 million :",nrow(filtered_players)))
head(filtered_players)

#------------------------------------------------------------------------------------------#

#Identify the dependent & independent variables and use reshaping techniques and create a new data frame by joining those variables from your dataset.


players_ds_personal <- players_ds[, c("player_id", "first_name", "last_name", "country_of_birth")]
players_ds_club <- players_ds[, c("player_id", "country_of_citizenship", "current_club_name", "current_club_domestic_competition_id")]

#merge dataframe
players_ds_merged <- merge(players_ds_personal, players_ds_club, by = "player_id")

head(players_ds_merged)

#------------------------------------------------------------------------------------------#

#Remove missing values in your dataset.
#remove players who do not have a market_value
players_ds_marketvalue <- players_ds %>% filter (!is.na(market_value_in_eur))
head(players_ds_marketvalue)
#remove rows with ant missing values
players_ds_nonmissing <- na.omit(players_ds)
head(players_ds_nonmissing)

players_ds <- players_ds_nonmissing

#------------------------------------------------------------------------------------------#

#Identify and remove duplicated data in your dataset

players_duplicates <- duplicated(players_ds)
no_of_duplicates <- sum(players_duplicates)
print(paste("No of duplicated rows ",no_of_duplicates))
players_ds_duplicates <- players_ds[players_duplicates,]
print(players_ds_duplicates)

#remove duplicates
players_ds_unique1 <- players_ds[!players_duplicates,]
head(players_ds_unique1)
players_ds_unique2 <- unique(players_ds)
head(players_ds_unique2)

players_ds <- players_ds_unique1

#------------------------------------------------------------------------------------------#

#Reorder multiple rows in descending order

players_ds <- players_ds %>% arrange(desc(market_value_in_eur),desc(highest_market_value_in_eur))

head(players_ds)

#------------------------------------------------------------------------------------------#

#Rename some of the column names in your dataset

players_ds <- players_ds %>% rename ( full_name = name , birth_city = city_of_birth , preferred_foot = foot)

head(players_ds)

#------------------------------------------------------------------------------------------#

#Add new variables in your data frame by using a mathematical function (for e.g. – multiply an existing column by 2 and add it as a new variable to your data frame)

players_ds <- players_ds %>% mutate (market_value_doubled = market_value_in_eur * 2)

head(players_ds)

#------------------------------------------------------------------------------------------#

#Create a training set using random number generator engine.

set.seed(513)

# Number of rows in the dataset
print(paste("Total no. of rows:",nrow(players_ds)))

train_indices <- sample(nrow(players_ds), size = 0.7 * nrow(players_ds), replace = FALSE)

training_set <- players_ds[train_indices, ]

print(paste("Training set rows",nrow(training_set)))

head(training_set)

#------------------------------------------------------------------------------------------#

#Print the summary statistics of your dataset

summary(players_ds)


#------------------------------------------------------------------------------------------#

#Use any of the numerical variables from the dataset and perform the following statistical functions 

#Mean
mean_market_value <- mean(players_ds$market_value_in_eur)
print(paste("The mean value of the market values is ",mean_market_value))

#Median
median_market_value <- median(players_ds$market_value_in_eur)
print(paste("The median value of the market values is ", median_market_value))

#Mode
mode_market_value <- Mode(players_ds$market_value_in_eur)
print(paste("The mode of the market values is ",mode_market_value))

#Range

range_market_value <- range(players_ds$market_value_in_eur)
print(paste("The range of the market values is [", range_market_value[1], " - ", range_market_value[2],"]"))


#------------------------------------------------------------------------------------------#

#Plot a scatter plot for any 2 variables in your dataset

#Plot graph market value vs height 
ggplot(players_ds, aes(x = height_in_cm, y = market_value_in_eur)) +
  geom_point(color = "black", size = 1) +        # Points for players
  labs(title = "Market Value vs. Height of Football Players",
       x = "Height (cm)",
       y = "Market Value (EUR)") +
  scale_y_continuous(labels = label_number(scale_cut = cut_short_scale())) + # Format y-axis labels
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))




#------------------------------------------------------------------------------------------#

#Plot a bar plot for any 2 variables in your dataset

# Extract the year of birth from the date_of_birth column
players_ds <- players_ds %>%
  mutate(year_of_birth = year(as.Date(date_of_birth)))

# Aggregate the data
aggregated_data <- players_ds %>%
  group_by(year_of_birth, position) %>%
  summarise(player_count = n())

# Remove empty values
aggregated_data<-na.omit(aggregated_data)

#Plot the graph No of players vs Year of Birth
ggplot(aggregated_data, aes(x = year_of_birth, y = player_count, fill = position)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Number of Players in Each Position by Year of Birth",
       x = "Year of Birth",
       y = "Number of Players",
       fill = "Position") +
  scale_x_continuous(breaks = seq(min(aggregated_data$year_of_birth), max(aggregated_data$year_of_birth), by = 2)) +
  theme(axis.text.x = element_text(angle = 75, hjust = 1))

#------------------------------------------------------------------------------------------#


# Calculate Pearson correlation coefficient
# Calculate the Pearson correlation between market_value and highest_market_value

correlation <- cor(players_ds$market_value_in_eur, players_ds$highest_market_value_in_eur, method = "pearson")

print(paste("The correlation coefficient is", correlation))

#------------------------------------------------------------------------------------------#
```


